workflows:
  distance_travel_log:
    name: Distance Travel Log
    instance_type: mac_pro
    max_build_duration: 50
    environment:
      groups:
        - keystore_credentials
        - app_store_credentials
      vars:
        GOOGLE_PLAY_TRACK: "beta"
      flutter: stable
      xcode: latest
      cocoapods: default
